[tool.black]
line-length = 140
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | docs
)/
'''

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["pynessie"]
omit = ["pynessie/auth/*.py"]

[tool.coverage.report]
show_missing = true
fail_under = 80

# https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml
[[tool.mypy.overrides]]
module = [
    'botocore.*',
    'confuse.*',
    'marshmallow_oneofschema.*',
    'requests_aws4auth.*',
    'assertpy.*',
    'testcontainers.*',
]
ignore_missing_imports = true
